### ISSUE TITLE
lazy-fixture breaks all the fixtures with autouse=True

### ISSUE THREAD

**Issue by lefterisnik** [TvoroG/pytest-lazy-fixture#11]
In my current project I have some fixtures which they use `autouse=True`. eg:

```
def setup(autouse=True):
     self.var = 15
```

After installing `pytest-lazy-fixture`, my tests can't find the `self.var` variable. If I remove the `autouse=True` and pass the fixture to my tests all work fine.

Any ideas?

**Comment by TvoroG** [comment]
@lefterisnik thanks for reporting it. I'll take a look as soon as possible

**Comment by lefterisnik** [comment]
HI @TvoroG,

I have noticed that you have tests about the `autouse=True` for fixtures outside of classes. My problem occurs when I use the above function inside a class. eg:

```
class TestModels(object):
     
    @pytest.fixture(autouse=True)
    def setup(self):
        self.var = 15 

    def test_model(self):
        self.var -> here the variable is undefined
```

I hope this could help you to reproduce the error.

**Comment by TvoroG** [comment]
@lefterisnik can you please check out the master branch? Is it fixed the bugs? If yes I'll upload new code to pypi

**Comment by lefterisnik** [comment]
Hi @TvoroG,

You are awesome. It fixes all the bugs except the `pytest.mark.skip`. 

About this, I have noticed that after the second test with `pytest.mark.skip` the pytest fails.

For example:

```
class TestModels(object):
    @pytest.mark.skip(reason='whatever')
    def test_model_1(self):
        pass

    @pytest.mark.skip(reason='whatever')
    def test_model_2(self):
         pass

    def test_model_3(self):   # here it will fail
         pass
```

I am not 100% sure about the above. I am just telling what I have noticed.

Thanks any way, great work. You saved me.

Are there any plans to embed this on pytest? 

Thanks,
lefteris

**Comment by lefterisnik** [comment]
I made a small PR, adding some tests after the `pytest.mark.skip` and right now the tests are failing. So the problem occurs on tests after the `pytest.mark.skip`

**Comment by TvoroG** [comment]
Thanks for your help, @lefterisnik! I'll check this out.

> Are there any plans to embed this on pytest?

I think pytest core contributors have their own thoughts how it should be implemented

**Comment by TvoroG** [comment]
@lefterisnik, here a quick fixes of tests https://github.com/TvoroG/pytest-lazy-fixture/commit/d35d34d0839717059203821cdcb96e8fc6309bea. If you had the same traceback as in tests before, you can fix it by passing tuple to `pytest.mark.parametrize` instead of a single element.
I'll try to dig deeper why is that happening, because it should accept single element if there is just one arg name in `parametrize`.

**Comment by TvoroG** [comment]
@lefterisnik, finally fixed it :) you can check out the master

**Comment by lefterisnik** [comment]
Hi @TvoroG, 

You are awesome. Everything is working properly. Thanks a lot.

Thanks,
Lefteris
