### ISSUE TITLE
prepare for the deprecation/removal of the pytest_namespace hook

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [TvoroG/pytest-lazy-fixture#16]
in pytest we are in the process of deprecating the pytest_namespace hook, so this plugin would need a new location for its api that works when that hook is removed

**Comment by TvoroG** [comment]
Hi! Thanks for informing me!
So one day pytest will stop invoking pytest_namespace and the right way of using these plugins would be just importing them?

**Comment by RonnyPfannschmidt** [comment]
@TvoroG correct

**Comment by YannickJadoul** [comment]
If anyone else would be encountering the same error as me: it seems that `pytest.lazyfixture` is now being added áfter `conftest.py` (cfr. https://docs.pytest.org/en/latest/deprecations.html#pytest-namespace). 

So to use `lazyfixture` to create ['globally-shared fixtures'](https://docs.pytest.org/en/latest/fixture.html#conftest-py-sharing-fixture-functions), you will have to import `pytest_lazyfixture` and use `pytest_lazyfixture.lazyfixture` (if I got that correctly?)

**Comment by jmehnle** [comment]
> If anyone else would be encountering the same error as I am: it seems that `pytest.lazyfixture` is now being added áfter `conftest.py` (cfr. https://docs.pytest.org/en/latest/deprecations.html#pytest-namespace).
> 
> So to use `lazyfixture` to create ['globally-shared fixtures'](https://docs.pytest.org/en/latest/fixture.html#conftest-py-sharing-fixture-functions), you will have to import `pytest_lazyfixture` and use `pytest_lazyfixture.lazyfixture` (if I got that correctly?)

I had the exact same problem: I was trying to use `pytest.lazy_fixture` in `conftest.py`. Importing it from `pytest_lazyfixture` instead worked!

**Comment by piotr-dobrogost** [comment]
_deprecate pytest_namespace alltogether_ – https://github.com/pytest-dev/pytest/issues/2639
_remove pytest namespace hook_ – https://github.com/pytest-dev/pytest/pull/4421
_#4421: Removed the implementation of the pytest_namespace hook._ (note from changelog of version 4.1.0) –
 https://docs.pytest.org/en/stable/changelog.html#id648

**Comment by z33kz33k** [comment]
@TvoroG I appreciate your hard work. I really do. But, pls, **do update** the README. Thanks in advance.

**Comment by RonnyPfannschmidt** [comment]
closing this as it seems to be resolved
