### ISSUE TITLE
Make LazyFixture iterable

### ISSUE THREAD

**Issue by michael-k** [TvoroG/pytest-lazy-fixture#6]
This does work now:

```python
@pytest.mark.parametrize('arg1', [
   pytest.lazy_fixture('needs_db')
])
@pytest.mark.django_db
def test_some(arg1):
    assert ...
```

But it's not quite what I need.  The fixture `needs_db` returns a list and I'd like to parametrize `test_some` with that list:

```python
@pytest.mark.parametrize('arg1', pytest.lazy_fixture('needs_db'))
@pytest.mark.django_db
def test_some(arg1):
    assert ...
```

This fails: `TypeError: 'LazyFixture' object is not iterable`

Is it possible to support this use case?  I'm not familiar with pytest's internals. :/

**Comment by TvoroG** [comment]
@michael-k thanks again for reporting a bug :)  I'll take a look

**Comment by TvoroG** [comment]
Well, I think I've just now realized what your use case :) Do you want to parametrize test with some data from db? If so, it's not quite possible. When `pytest.mark.parametrize` wants to iterate through your data (argument values), `pytest_django` autouse fixtures are not yet executed, so there is no even test db.

**Comment by michael-k** [comment]
That's what I feared. :/
