### ISSUE TITLE
Possible to expand the fixture return value in parametrize?

### ISSUE THREAD

**Issue by schtibe** [TvoroG/pytest-lazy-fixture#9]
I would like to parametrize a test with the return value of a fixture.

Example:
```
@pytest.fixture
def links(browser): // assume broser was a fixture
    return browser.find_by_tag('a')

@pytest.mark.parametrize("link", links) // here expand the links fixture return value
def test_func(link):
     // test that link here
```

Is this possible with pytest-lazy-fixture? (or maybe even pytest itself?) Or might it be a nice feature?

**Comment by TvoroG** [comment]
Hi! Yes, you can do it with pytest-lazy-fixture:
```python
@pytest.fixture
def links(browser): # assume browser was a fixture
    return browser.find_by_tag('a')

@pytest.mark.parametrize("link", [
    pytest.lazy_fixture('links')
]) # here expand the links fixture return value
def test_func(link):
     # test that link here
```

**Comment by schtibe** [comment]
This way i get following error:

```
   return [LazyFixture(name) for name in names]
E   TypeError: 'function' object is not iterable
```

**Comment by TvoroG** [comment]
There was a similar issue: https://github.com/TvoroG/pytest-lazy-fixture/issues/6. For now It's not possible to implement this feature.

**Comment by TvoroG** [comment]
If you have some other issues or questions feel free to reopen it or create another one

**Comment by tovmeod** [comment]
I'm interested in something like that? did the situation change? is it possible to implement this today? if not, why not?

**Comment by TvoroG** [comment]
Check out https://github.com/pytest-dev/pytest/issues/4050. I think the main reason here is that you want to generate test cases during runtime, and pytest can do it only during the collection stage. Although I'm not sure.

**Comment by jxramos** [comment]
It is looking like this collection stage constraint is indeed what may be lurking here...

> per design all parametization happens at collection time
> [StackOverflow Answer: pytest test needs parametrization at collection phase and at setup time](https://stackoverflow.com/a/31746703/1330381)
